db:
  image: redis
  ports:
    - "6379"

api:
  build: .
  command: coffee ./pushd.coffee
  volumes:
    - .:/src
  ports:
    - "8000:8000"
  links:
    - db
  env_file:
    ./settings-sample.env.example
